stages:
  - build
  - quality_gate
  - deploy 

dockerfile:deploy:hub:develop:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - export DOCKER_BUILD="1"
    - ls -la
    - ./update.sh
  only:
    - develop

dockerfile:deploy:hub:master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - export DOCKER_BUILD="1"
    - export DOCKER_PUSH="1"
    - ./update.sh
  only:
    - master