---
# We assume to have a traefik network on our 
# development machine to expose robert2.treafik.me in SSL
# More information here: https://zestedesavoir.com/billets/3355/traefik-v2-https-ssl-en-localhost/
# You can up this stack from the ./run-dev.sh file
version: '3.7'
services:
  app:
    image: robert2
    build:
      context: .
      dockerfile: ./images/0.21.2-php8-apache-buster/Dockerfile
    labels:
      traefik.enable: true
      traefik.http.routers.robert2.rule: Host(`robert2.traefik.me`)
      traefik.http.services.webmonitor.loadbalancer.server.port: 80
    networks:
      - default

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootmdp
      MYSQL_DATABASE: robert2_db
      MYSQL_USER: robert2_usr
      MYSQL_PASSWORD: mdpuserpassword
    volumes:
      - robert2_data:/var/lib/mysql
    networks:
      - default

# Docker Networks
networks:
  default:

# Docker volumes
volumes:
  robert2_data:
